import {
  WORLD_PHYSICAL_FEATURES,
  WORLD_INDUSTRIAL_BELTS,
  WORLD_TRANSPORT_ROUTES,
  WORLD_OCEANS_DATA,
  WorldPhysicalFeature,
  WorldIndustrialBelt,
  WorldTransportRoute,
  WorldOceanRecord,
} from './worldGeographyData';

export type LandmarkCategory = 'physical' | 'ocean' | 'industrial' | 'transport';

export interface GlobalLandmark {
  id: string;
  name: string;
  shortName: string;
  category: LandmarkCategory;
  typeLabel: string;
  region: string;
  coordinates: { x: number; y: number }; // SVG canvas coordinates (0-100%)
  gps: {
    lat: number;
    lng: number;
    latLabel: string;
    lngLabel: string;
  };
  keyMetric: string;
  highlights: string;
  significance: string;
  sourceType: 'physical' | 'ocean' | 'industrial' | 'transport';
  googleMapsUrl: string;
}

// Helper to format Google Maps satellite search URL
const getGMapUrl = (lat: number, lng: number) =>
  `https://www.google.com/maps/search/?api=1&query=${lat},${lng}`;

export const GLOBAL_LANDMARKS_CATALOG: GlobalLandmark[] = [
  // ================= NATURAL WONDERS & PHYSICAL FEATURES =================
  {
    id: 'himalayas',
    name: 'The Himalayas & Mount Everest',
    shortName: 'Mt. Everest & Himalayas',
    category: 'physical',
    typeLabel: 'Fold Mountain Range',
    region: 'Asia (Nepal / China / India)',
    coordinates: { x: 73, y: 44 },
    gps: { lat: 27.9881, lng: 86.925, latLabel: '27°59′N', lngLabel: '86°55′E' },
    keyMetric: '8,848.86 m elevation | 14 peaks >8,000 m',
    highlights: 'Formed by Indian Plate colliding into Eurasian Plate at ~5 cm/yr.',
    significance: 'Water Tower of Asia; feeds Indus, Ganges, Brahmaputra & Yangtze rivers.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(27.9881, 86.925),
  },
  {
    id: 'andes',
    name: 'The Andes Mountains & Aconcagua',
    shortName: 'Andes Mountains',
    category: 'physical',
    typeLabel: 'Continental Cordillera',
    region: 'South America (Venezuela to Chile)',
    coordinates: { x: 28, y: 72 },
    gps: { lat: -32.6532, lng: -70.0109, latLabel: '32°39′S', lngLabel: '70°00′W' },
    keyMetric: '7,000 km length | Mt. Aconcagua: 6,961 m',
    highlights: 'Longest continental mountain range, formed by Nazca Plate subduction.',
    significance: 'Houses world-class copper and lithium brine reserves; creates Atacama rain shadow.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(-32.6532, -70.0109),
  },
  {
    id: 'rockies',
    name: 'Rocky Mountains & Continental Divide',
    shortName: 'Rocky Mountains',
    category: 'physical',
    typeLabel: 'Orogenic Mountain Belt',
    region: 'North America (Canada / USA)',
    coordinates: { x: 20, y: 32 },
    gps: { lat: 39.1178, lng: -106.4454, latLabel: '39°07′N', lngLabel: '106°26′W' },
    keyMetric: '4,800 km length | Mt. Elbert: 4,401 m',
    highlights: 'Formed during the Laramide Orogeny (80–55 million years ago).',
    significance: 'Forms the Continental Divide of the Americas separating Pacific and Atlantic watersheds.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(39.1178, -106.4454),
  },
  {
    id: 'alps',
    name: 'European Alps & Mont Blanc',
    shortName: 'European Alps',
    category: 'physical',
    typeLabel: 'Alpine Fold Mountains',
    region: 'Europe (France / Switzerland / Italy / Austria)',
    coordinates: { x: 51, y: 33 },
    gps: { lat: 45.8326, lng: 6.8652, latLabel: '45°50′N', lngLabel: '6°52′E' },
    keyMetric: 'Mont Blanc: 4,808 m | Spans 8 European nations',
    highlights: 'Formed by African and Eurasian plate collision with classic glacial landforms.',
    significance: 'Headwaters of the Rhine, Rhône, and Danube rivers; vital European hydro power reservoir.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(45.8326, 6.8652),
  },
  {
    id: 'atlas',
    name: 'Atlas Mountains',
    shortName: 'Atlas Mountains',
    category: 'physical',
    typeLabel: 'Continental Fold Range',
    region: 'North Africa (Morocco / Algeria / Tunisia)',
    coordinates: { x: 47, y: 40 },
    gps: { lat: 31.06, lng: -7.9158, latLabel: '31°03′N', lngLabel: '7°55′W' },
    keyMetric: '2,500 km length | Toubkal: 4,167 m',
    highlights: 'Separates the Atlantic & Mediterranean coastlines from the hyper-arid Sahara Desert.',
    significance: 'Holds over 70% of the world’s phosphate reserves, critical for global agricultural fertilizer.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(31.06, -7.9158),
  },
  {
    id: 'nile-river',
    name: 'Nile River Basin & Delta',
    shortName: 'Nile River Basin',
    category: 'physical',
    typeLabel: 'River Basin System',
    region: 'Africa (Tanzania / Uganda / Sudan / Egypt)',
    coordinates: { x: 58, y: 46 },
    gps: { lat: 15.6047, lng: 32.5324, latLabel: '15°36′N', lngLabel: '32°31′E' },
    keyMetric: '6,650 km length (Longest river on Earth)',
    highlights: 'Fed by White Nile (Lake Victoria, Tanzania) and Blue Nile (Ethiopian Highlands).',
    significance: 'Sustained human civilization for 5,000+ years; home to Aswan Dam and GERD mega-reservoirs.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(15.6047, 32.5324),
  },
  {
    id: 'amazon-river',
    name: 'Amazon River & Tropical Rainforest',
    shortName: 'Amazon Rainforest Basin',
    category: 'physical',
    typeLabel: 'River Basin & Biome',
    region: 'South America (Brazil / Peru / Colombia)',
    coordinates: { x: 33, y: 58 },
    gps: { lat: -3.4653, lng: -62.2159, latLabel: '3°28′S', lngLabel: '62°13′W' },
    keyMetric: 'Discharge: 209,000 m³/s (20% of global river flow)',
    highlights: 'Basin covers 7,000,000 km²; world’s largest equatorial carbon sink and biodiversity reserve.',
    significance: 'Critical regulator of global precipitation patterns and atmospheric oxygen cycles.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(-3.4653, -62.2159),
  },
  {
    id: 'yangtze-river',
    name: 'Yangtze River & Three Gorges',
    shortName: 'Yangtze River',
    category: 'physical',
    typeLabel: 'River System & Hydro Dam',
    region: 'Asia (China)',
    coordinates: { x: 79, y: 43 },
    gps: { lat: 30.8266, lng: 111.0028, latLabel: '30°49′N', lngLabel: '111°00′E' },
    keyMetric: '6,300 km length | Three Gorges: 22,500 MW',
    highlights: 'Originates on the Tibetan Plateau and discharges into the East China Sea at Shanghai.',
    significance: 'Economic belt accounts for >40% of China’s GDP and primary irrigation corridor.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(30.8266, 111.0028),
  },
  {
    id: 'congo-river',
    name: 'Congo River & Equatorial Basin',
    shortName: 'Congo River Basin',
    category: 'physical',
    typeLabel: 'Deep River Basin',
    region: 'Central Africa (DRC / Congo / Angola)',
    coordinates: { x: 54, y: 58 },
    gps: { lat: -4.4419, lng: 15.2663, latLabel: '4°26′S', lngLabel: '15°16′E' },
    keyMetric: '>220 m depth (Deepest on Earth) | 41,000 m³/s flow',
    highlights: 'Crosses the equator twice; surrounded by the planet’s second-largest rainforest.',
    significance: 'Highest hydroelectric potential on Earth (Grand Inga proposal: 40,000 MW).',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(-4.4419, 15.2663),
  },
  {
    id: 'sahara-desert',
    name: 'The Sahara Desert',
    shortName: 'Sahara Desert',
    category: 'physical',
    typeLabel: 'Subtropical Hot Desert',
    region: 'North Africa',
    coordinates: { x: 50, y: 44 },
    gps: { lat: 23.4162, lng: 25.6628, latLabel: '23°25′N', lngLabel: '25°40′E' },
    keyMetric: '9,200,000 km² (World’s largest hot desert)',
    highlights: 'Controlled by descending atmospheric Hadley Cells producing intense aridity.',
    significance: 'Contains the Nubian Sandstone Fossil Aquifer and premier global solar radiation potential.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(23.4162, 25.6628),
  },
  {
    id: 'atacama-desert',
    name: 'Atacama Desert (Hyper-Arid Plateau)',
    shortName: 'Atacama Desert',
    category: 'physical',
    typeLabel: 'Coastal Rain Shadow Desert',
    region: 'South America (Northern Chile)',
    coordinates: { x: 28, y: 70 },
    gps: { lat: -24.5, lng: -69.25, latLabel: '24°30′S', lngLabel: '69°15′W' },
    keyMetric: 'Driest non-polar desert (some spots <1 mm rain/yr)',
    highlights: 'Double rain-shadow formed by the Andes and the cold oceanic Humboldt Current.',
    significance: 'World hub for deep-space astronomical observatories (ALMA) and global lithium reserves.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(-24.5, -69.25),
  },
  {
    id: 'mariana-trench',
    name: 'Mariana Trench & Challenger Deep',
    shortName: 'Mariana Trench',
    category: 'physical',
    typeLabel: 'Oceanic Subduction Trench',
    region: 'Western Pacific Ocean (Micronesia)',
    coordinates: { x: 84, y: 47 },
    gps: { lat: 11.3733, lng: 142.5917, latLabel: '11°22′N', lngLabel: '142°35′E' },
    keyMetric: '10,994 m depth (Deepest point on Earth)',
    highlights: 'Pacific Plate subducts beneath the Mariana Plate; hydrostatic pressure exceeds 1,086 bar.',
    significance: 'Earth’s ultimate abyss; 2,146 m deeper than Mount Everest is tall.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(11.3733, 142.5917),
  },
  {
    id: 'puerto-rico-trench',
    name: 'Puerto Rico Trench & Milwaukee Deep',
    shortName: 'Puerto Rico Trench',
    category: 'physical',
    typeLabel: 'Oceanic Subduction Trench',
    region: 'Atlantic Ocean (Caribbean Boundary)',
    coordinates: { x: 34, y: 44 },
    gps: { lat: 19.84, lng: -66.5, latLabel: '19°50′N', lngLabel: '66°30′W' },
    keyMetric: '8,380 m depth (Deepest point in Atlantic)',
    highlights: 'Oblique subduction zone between North American and Caribbean plates.',
    significance: 'Major seismic hazard capable of generating Atlantic megathrust tsunamis.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(19.84, -66.5),
  },
  {
    id: 'java-sunda-trench',
    name: 'Java (Sunda) Trench',
    shortName: 'Java Trench',
    category: 'physical',
    typeLabel: 'Oceanic Subduction Trench',
    region: 'Indian Ocean (Off Sumatra / Java)',
    coordinates: { x: 76, y: 56 },
    gps: { lat: -10.3167, lng: 109.9667, latLabel: '10°19′S', lngLabel: '109°58′E' },
    keyMetric: '7,190 m depth (Deepest in Indian Ocean)',
    highlights: 'Australian Plate subducting beneath the Sunda Plate at 6–7 cm/year.',
    significance: 'Triggered the historic 2004 Indian Ocean Mw 9.1 megathrust earthquake and tsunami.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(-10.3167, 109.9667),
  },
  {
    id: 'pacific-ring-of-fire',
    name: 'Pacific Ring of Fire',
    shortName: 'Ring of Fire',
    category: 'physical',
    typeLabel: 'Tectonic Subduction Belt',
    region: 'Circum-Pacific Rim',
    coordinates: { x: 86, y: 46 },
    gps: { lat: 35.6762, lng: 139.6503, latLabel: '35°40′N', lngLabel: '139°39′E' },
    keyMetric: '40,000 km belt | 75% active volcanoes | 90% quakes',
    highlights: 'Horse-shoe arc of convergent subduction zones encircling the entire Pacific Ocean basin.',
    significance: 'Drives global volcanism, geothermal energy systems, and tectonic mountain building.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(35.6762, 139.6503),
  },
  {
    id: 'mid-atlantic-ridge',
    name: 'Mid-Atlantic Spreading Ridge',
    shortName: 'Mid-Atlantic Ridge',
    category: 'physical',
    typeLabel: 'Divergent Plate Boundary',
    region: 'Atlantic Ocean (Iceland to South Atlantic)',
    coordinates: { x: 40, y: 45 },
    gps: { lat: 38.0, lng: -30.0, latLabel: '38°00′N', lngLabel: '30°00′W' },
    keyMetric: '16,000 km underwater mountain range',
    highlights: 'Seafloor spreading center where American and Eurasian/African plates pull apart.',
    significance: 'Surfaces above sea level in Iceland, powering 100% renewable geothermal heating & electricity.',
    sourceType: 'physical',
    googleMapsUrl: getGMapUrl(38.0, -30.0),
  },

  // ================= WORLD OCEAN BASINS =================
  {
    id: 'pacific-ocean',
    name: 'Pacific Ocean (Largest & Deepest)',
    shortName: 'Pacific Ocean Basin',
    category: 'ocean',
    typeLabel: 'Major Ocean Basin',
    region: 'Global (Between Americas and Asia/Oceania)',
    coordinates: { x: 12, y: 55 },
    gps: { lat: 0.0, lng: -160.0, latLabel: '0°00′N', lngLabel: '160°00′W' },
    keyMetric: '168,723,000 km² (46.6% of ocean surface) | 4,280 m avg depth',
    highlights: 'Covers more area than all Earth’s land masses combined; contains Challenger Deep.',
    significance: 'Drives El Niño-Southern Oscillation (ENSO) and absorbs vast quantities of atmospheric heat.',
    sourceType: 'ocean',
    googleMapsUrl: getGMapUrl(0.0, -160.0),
  },
  {
    id: 'atlantic-ocean',
    name: 'Atlantic Ocean & Mid-Ocean Basin',
    shortName: 'Atlantic Ocean Basin',
    category: 'ocean',
    typeLabel: 'Major Ocean Basin',
    region: 'Global (Between Americas and Europe/Africa)',
    coordinates: { x: 38, y: 48 },
    gps: { lat: 14.5994, lng: -28.6731, latLabel: '14°35′N', lngLabel: '28°40′W' },
    keyMetric: '85,133,000 km² (23.5% of ocean surface) | 3,646 m avg depth',
    highlights: 'S-shaped ocean basin divided into North and South by the equatorial countercurrents.',
    significance: 'Hosts the Atlantic Meridional Overturning Circulation (AMOC) regulating European climate.',
    sourceType: 'ocean',
    googleMapsUrl: getGMapUrl(14.5994, -28.6731),
  },
  {
    id: 'indian-ocean',
    name: 'Indian Ocean (Tanzania Coastal Waters)',
    shortName: 'Indian Ocean Basin',
    category: 'ocean',
    typeLabel: 'Major Ocean Basin',
    region: 'Global (Touches Tanzania, Kenya, India, Australia)',
    coordinates: { x: 67, y: 65 },
    gps: { lat: -20.0, lng: 80.0, latLabel: '20°00′S', lngLabel: '80°00′E' },
    keyMetric: '70,560,000 km² (19.5% of ocean surface) | 3,741 m avg depth',
    highlights: 'Warmest ocean on Earth; washes Tanzania’s coast (Dar es Salaam, Zanzibar, Tanga, Mtwara).',
    significance: 'Monsoonal climate driver for East Africa and South Asia; carries 50% of global oil shipments.',
    sourceType: 'ocean',
    googleMapsUrl: getGMapUrl(-20.0, 80.0),
  },
  {
    id: 'southern-ocean',
    name: 'Southern Ocean (Antarctic Circumpolar)',
    shortName: 'Southern Ocean Basin',
    category: 'ocean',
    typeLabel: 'Circumpolar Ocean Basin',
    region: 'Antarctic Waters (South of 60°S)',
    coordinates: { x: 50, y: 92 },
    gps: { lat: -65.0, lng: 90.0, latLabel: '65°00′S', lngLabel: '90°00′E' },
    keyMetric: '21,960,000 km² | Factorian Deep: 7,434 m',
    highlights: 'Only ocean that completely circles the globe without interruption by any landmass.',
    significance: 'Antarctic Circumpolar Current drives the global marine conveyor belt and oxygenates deep sea.',
    sourceType: 'ocean',
    googleMapsUrl: getGMapUrl(-65.0, 90.0),
  },
  {
    id: 'arctic-ocean',
    name: 'Arctic Ocean & Polar Ice Cap',
    shortName: 'Arctic Ocean Basin',
    category: 'ocean',
    typeLabel: 'Polar Ocean Basin',
    region: 'North Polar Region',
    coordinates: { x: 50, y: 8 },
    gps: { lat: 85.0, lng: 0.0, latLabel: '85°00′N', lngLabel: '0°00′E' },
    keyMetric: '15,558,000 km² | Molloy Deep: 5,550 m',
    highlights: 'Smallest, shallowest, and coldest ocean; covered in seasonal and multi-year sea ice.',
    significance: 'Global albedo thermostat; critical bellwether for polar amplification and planetary warming.',
    sourceType: 'ocean',
    googleMapsUrl: getGMapUrl(85.0, 0.0),
  },

  // ================= INDUSTRIAL BELTS & MANUFACTURING HUBS =================
  {
    id: 'silicon-valley',
    name: 'Silicon Valley Innovation Belt',
    shortName: 'Silicon Valley Hub',
    category: 'industrial',
    typeLabel: 'High-Tech Industrial Hub',
    region: 'North America (California, USA)',
    coordinates: { x: 14, y: 35 },
    gps: { lat: 37.3861, lng: -122.0839, latLabel: '37°23′N', lngLabel: '122°05′W' },
    keyMetric: 'Over $3 Trillion enterprise valuation | Global leader in AI & microchips',
    highlights: 'Agglomeration economy of venture capital, Stanford research, and semiconductor giants.',
    significance: 'Generates foundational microprocessors, artificial intelligence platforms, and operating systems.',
    sourceType: 'industrial',
    googleMapsUrl: getGMapUrl(37.3861, -122.0839),
  },
  {
    id: 'ruhr-valley',
    name: 'Ruhr Industrial Valley & Rhine Hub',
    shortName: 'Ruhr Valley Axis',
    category: 'industrial',
    typeLabel: 'Heavy Manufacturing & Clean Energy',
    region: 'Western Europe (Germany)',
    coordinates: { x: 50, y: 28 },
    gps: { lat: 51.4556, lng: 7.0116, latLabel: '51°27′N', lngLabel: '7°00′E' },
    keyMetric: 'Largest European industrial conurbation (5.1 million residents)',
    highlights: 'Historic coal-and-steel engine transformed into high-tech chemicals, robotics & green hydrogen.',
    significance: 'Model of European post-industrial structural transition and heavy industrial logistics.',
    sourceType: 'industrial',
    googleMapsUrl: getGMapUrl(51.4556, 7.0116),
  },
  {
    id: 'pearl-river-delta',
    name: 'Pearl River Delta (Guangdong Greater Bay Area)',
    shortName: 'Pearl River Delta Megacity',
    category: 'industrial',
    typeLabel: 'World Workshop & Electronics',
    region: 'East Asia (Shenzhen / Guangzhou / HK)',
    coordinates: { x: 80, y: 43 },
    gps: { lat: 22.5431, lng: 114.0579, latLabel: '22°32′N', lngLabel: '114°03′E' },
    keyMetric: 'Produces >40% of global consumer electronics | $2T GDP',
    highlights: 'Shenzhen hardware ecosystem integrated with Guangzhou manufacturing and HK finance.',
    significance: 'The world’s supreme export workshop for hardware, telecommunications, and electric vehicles.',
    sourceType: 'industrial',
    googleMapsUrl: getGMapUrl(22.5431, 114.0579),
  },
  {
    id: 'tokyo-yokohama',
    name: 'Tokyo-Yokohama Keihin Industrial Belt',
    shortName: 'Tokyo-Yokohama Belt',
    category: 'industrial',
    typeLabel: 'Precision Robotics & Automotive',
    region: 'East Asia (Japan)',
    coordinates: { x: 86, y: 35 },
    gps: { lat: 35.4437, lng: 139.638, latLabel: '35°26′N', lngLabel: '139°38′E' },
    keyMetric: 'World’s most populous metropolitan economy (38M people)',
    highlights: 'Clustered around Tokyo Bay with deep-water container terminals and advanced R&D.',
    significance: 'Global benchmark for industrial robotics, precision optics, and automotive automation.',
    sourceType: 'industrial',
    googleMapsUrl: getGMapUrl(35.4437, 139.638),
  },
  {
    id: 'great-lakes-belt',
    name: 'North American Great Lakes Industrial Belt',
    shortName: 'Great Lakes Industrial Belt',
    category: 'industrial',
    typeLabel: 'Automotive & Heavy Industry',
    region: 'North America (USA / Canada)',
    coordinates: { x: 24, y: 32 },
    gps: { lat: 41.8781, lng: -87.6298, latLabel: '41°52′N', lngLabel: '87°37′W' },
    keyMetric: 'Access to 20% of world’s surface freshwater via Great Lakes St. Lawrence Seaway',
    highlights: 'Chicago, Detroit, Cleveland, and Toronto connected by inland maritime iron ore shipping.',
    significance: 'Automotive manufacturing cradle transitioning into battery and electric propulsion plants.',
    sourceType: 'industrial',
    googleMapsUrl: getGMapUrl(41.8781, -87.6298),
  },

  // ================= MARITIME CHOKEPOINTS, CANALS & TRANSPORT ROUTES =================
  {
    id: 'suez-canal',
    name: 'The Suez Canal (Mediterranean - Red Sea)',
    shortName: 'Suez Maritime Canal',
    category: 'transport',
    typeLabel: 'Maritime Sea-Level Canal',
    region: 'Middle East / North Africa (Egypt)',
    coordinates: { x: 56, y: 41 },
    gps: { lat: 30.5852, lng: 32.2654, latLabel: '30°35′N', lngLabel: '32°15′E' },
    keyMetric: 'Handles ~12% of global trade | 193.3 km length',
    highlights: 'Cuts 8,900 km off the journey between Europe and Asia by bypassing the Cape of Good Hope.',
    significance: 'Premier maritime trade artery; critical conduit for containerized goods and crude oil.',
    sourceType: 'transport',
    googleMapsUrl: getGMapUrl(30.5852, 32.2654),
  },
  {
    id: 'panama-canal',
    name: 'The Panama Canal (Atlantic - Pacific)',
    shortName: 'Panama Lock Canal',
    category: 'transport',
    typeLabel: 'Freshwater Lock Canal',
    region: 'Central America (Panama)',
    coordinates: { x: 26, y: 51 },
    gps: { lat: 9.1012, lng: -79.6952, latLabel: '9°06′N', lngLabel: '79°41′W' },
    keyMetric: '82 km length | Elevates ships 26 m via Gatun Lake locks',
    highlights: 'Eliminates treacherous 15,000 km voyage around Cape Horn at the tip of South America.',
    significance: 'Connects Pacific manufacturing hubs with Atlantic and US East Coast consumer markets.',
    sourceType: 'transport',
    googleMapsUrl: getGMapUrl(9.1012, -79.6952),
  },
  {
    id: 'strait-of-malacca',
    name: 'Strait of Malacca (Indian Ocean - Pacific)',
    shortName: 'Strait of Malacca',
    category: 'transport',
    typeLabel: 'Strategic Maritime Chokepoint',
    region: 'Southeast Asia (Singapore / Malaysia / Indonesia)',
    coordinates: { x: 77, y: 53 },
    gps: { lat: 1.43, lng: 102.89, latLabel: '1°25′N', lngLabel: '102°53′E' },
    keyMetric: 'Carries 30% of global maritime commerce & 80% of China’s oil imports',
    highlights: 'Narrow maritime funnel (only 2.8 km wide at Phillips Channel near Singapore).',
    significance: 'The busiest and most geostrategic trade chokepoint on planet Earth.',
    sourceType: 'transport',
    googleMapsUrl: getGMapUrl(1.43, 102.89),
  },
  {
    id: 'strait-of-hormuz',
    name: 'Strait of Hormuz (Persian Gulf Petroleum Gate)',
    shortName: 'Strait of Hormuz',
    category: 'transport',
    typeLabel: 'Energy Shipping Chokepoint',
    region: 'Middle East (Oman / Iran / UAE)',
    coordinates: { x: 64, y: 42 },
    gps: { lat: 26.5667, lng: 56.25, latLabel: '26°34′N', lngLabel: '56°15′E' },
    keyMetric: '21 million barrels of petroleum per day (21% of global petroleum consumption)',
    highlights: 'Sole sea passage from the Persian Gulf to the open ocean for Saudi, Iraqi, and Emirati crude.',
    significance: 'World’s most critical energy transit chokepoint; price shocks immediately impact global oil markets.',
    sourceType: 'transport',
    googleMapsUrl: getGMapUrl(26.5667, 56.25),
  },
  {
    id: 'strait-of-gibraltar',
    name: 'Strait of Gibraltar (Atlantic - Mediterranean)',
    shortName: 'Strait of Gibraltar',
    category: 'transport',
    typeLabel: 'Intercontinental Maritime Gate',
    region: 'Europe / Africa (Spain / Morocco / UK)',
    coordinates: { x: 45, y: 39 },
    gps: { lat: 35.9667, lng: -5.6, latLabel: '35°58′N', lngLabel: '5°36′W' },
    keyMetric: '14.3 km width at narrowest point | Pillars of Hercules',
    highlights: 'Connects the open Atlantic Ocean to the enclosed Mediterranean Sea basin.',
    significance: 'Vital naval gatekeeper and migratory corridor between European and African continents.',
    sourceType: 'transport',
    googleMapsUrl: getGMapUrl(35.9667, -5.6),
  },
  {
    id: 'bab-el-mandeb',
    name: 'Bab el-Mandeb Strait (Gate of Tears)',
    shortName: 'Bab el-Mandeb Strait',
    category: 'transport',
    typeLabel: 'Red Sea Gateway Chokepoint',
    region: 'Horn of Africa / Arabia (Djibouti / Yemen)',
    coordinates: { x: 59, y: 47 },
    gps: { lat: 12.5833, lng: 43.3333, latLabel: '12°35′N', lngLabel: '43°20′E' },
    keyMetric: 'Connects Indian Ocean to Red Sea & Suez Canal',
    highlights: 'Crucial nautical funnel between the Horn of Africa (Djibouti) and the Arabian Peninsula (Yemen).',
    significance: 'Any disruption here forces global shipping around South Africa’s Cape of Good Hope.',
    sourceType: 'transport',
    googleMapsUrl: getGMapUrl(12.5833, 43.3333),
  },
  {
    id: 'trans-siberian-railway',
    name: 'Trans-Siberian Railway Corridor',
    shortName: 'Trans-Siberian Rail',
    category: 'transport',
    typeLabel: 'Transcontinental Rail Trunk',
    region: 'Eurasia (Moscow to Vladivostok)',
    coordinates: { x: 70, y: 25 },
    gps: { lat: 52.287, lng: 104.305, latLabel: '52°17′N', lngLabel: '104°18′E' },
    keyMetric: '9,289 km length (Longest continuous railway line in the world)',
    highlights: 'Spans 8 time zones crossing the Ural Mountains, Siberian taiga, and Lake Baikal.',
    significance: 'Primary overland freight artery bridging European markets with the Russian Pacific coastline.',
    sourceType: 'transport',
    googleMapsUrl: getGMapUrl(52.287, 104.305),
  },
  {
    id: 'dubai-superhub',
    name: 'Dubai International Aviation Crossroads (DXB)',
    shortName: 'Dubai Global Superhub',
    category: 'transport',
    typeLabel: 'Intercontinental Air Hub',
    region: 'Middle East (United Arab Emirates)',
    coordinates: { x: 63, y: 42 },
    gps: { lat: 25.2532, lng: 55.3657, latLabel: '25°15′N', lngLabel: '55°21′E' },
    keyMetric: 'World’s busiest airport by international passenger traffic (>87M passengers/yr)',
    highlights: 'Situated within 8 hours flying time of two-thirds of the world’s population.',
    significance: 'Pinnacle superconnector linking Africa, Europe, Asia, and Australasia.',
    sourceType: 'transport',
    googleMapsUrl: getGMapUrl(25.2532, 55.3657),
  },
];
